### ISSUE TITLE
doesn't support chain calls

### ISSUE THREAD

**Issue by aostroukhov** [tonai/jquery-onend#1]
Plugin doesn't support chain calls like this
$(window)
.onEnd("resize", callBack, 200)
.onEnd("scroll", callBack, 200);

I fixed this by add "return" to this line:
return this.on.apply( this, onParams );

**Comment by tonai** [comment]
Thanks for your message.
I will check this soon.

**Comment by tonai** [comment]
Should be fix in v0.0.3.
